name: Publish Docker image
on:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Prepare build Tag
        id: build-tag
        run: |
          echo "::set-output name=tag::${{github.run_number}}_$(date +%Y-%m-%d)"

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to Docker Hub
        id: build-image-push
        env:
          DOCKERHUB_REGISTRY: andbeone
          DOCKERHUB_REPOSITORY: awscli
          IMAGE_TAG: ${{ steps.build-tag.outputs.tag}}
        run: |
          # Build a docker container and
          # push it to Docker Hub.
          docker build  -t $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG -t $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:latest .
          docker push $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG
          docker push $DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:latest
          echo "::set-output name=image::$DOCKERHUB_REGISTRY/$DOCKERHUB_REPOSITORY:$IMAGE_TAG"